language: php
sudo: false
dist: precise

php:
  - '7.0'
  - '7.1'
  - '7.2'

notifications:
  email:
    recipients:
      - wico0628@gmail.com
    on_success: change
    on_failure: always

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan config:clear
  - php artisan config:cache

script:
  - ./vendor/bin/phpunit

