language: php
php:
  - '7.1'

sudo: false

notifications:
  email:
    recipients:
      - wico0628@gmail.com
    on_success: change
    on_failure: always

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan config:clear
  - php artisan config:cache

script:
  - ./vendor/bin/phpunit

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - wico0628@gmail.com
    on_success: change
    on_failure: always


